blank_issues_enabled: false

contact_links:
  - name: ğŸ¤” Questions and Community Support
    url: https://cloudflex.io/discord
    about: If you have any questions, reach out to us on Discord inside the "#support" channel.

  - name: ğŸ’¡ Feature Request
    url: https://github.com/cloudflex/flexdev/discussions/categories/feature-requests
    about: Suggest a new feature for FlexDEV.

  - name: âš™ï¸ Service Request
    url: https://github.com/cloudflex/flexdev/discussions/categories/service-requests
    about: Request a new service integration for FlexDEV.

  - name: ğŸ”§ Improvements
    url: https://github.com/cloudflex/flexdev/discussions/categories/improvements
    about: Suggest improvements to existing features for FlexDEV.
